name: baseglobe
static_sites:
  - name: baseglobe
    github:
      branch: main
      deploy_on_push: true
      repo: thisyearnofear/thebaseglobe
    build_command: npm install && npx webpack
    output_dir: dist
    index_document: index.html
    error_document: index.html
    catchall_document: index.html
    environment_slug: node-js
    envs:
      - key: NODE_VERSION
        value: 18
    routes:
      - path: /*
        rewrite: /index.html
